# config
nginx:
 dockerfile: ./Dockerfile # путь до докер файла указываем относительно директории в build
 build: ./containers/nginx
 ports:
  - 80:80
 volumes:
  - ./logs:/etc/logs/nginx
 volumes_from:
  - fpm:rw
 environment:
  - NGINX_HOST=localhost
  - NGINX_PORT=80
 command: nginx -g "daemon off;" # Можно было указать в докер-фале, но можно и здесь)
 links:
  - fpm
fpm:
 dockerfile: ./Dockerfile
 build: ./containers/fpm
 ports: 
  - 9000:9000
 volumes:
  - ./code:/var/www:rw
composer:
 restart: 'no'
 build: ./containers/composer
 volumes_from:
  - fpm:rw
mongo:
 build: ./containers/mongo
